### ISSUE TITLE
Admin Roadmap

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/aime-core#98]
- [x] Designing a markdown parser abstraction.
- [x] Create server-side parsing of slides markdown syntax.
- [x] Build document edition routes.
- [x] Make document edition possible UI-wise.
- [x] Make document creation possible UI-wise.
- [x] Decide with @paulgirard for user's activation in migration.
